CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(21) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE INDEX idx_users_username ON users (username);

CREATE TABLE IF NOT EXISTS sessions (
    id VARCHAR(21) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
    user_id VARCHAR(21) COLLATE utf8mb4_bin NOT NULL,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_sessions_user_id ON sessions (user_id);

CREATE TABLE IF NOT EXISTS zones (
    id VARCHAR(21) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
    owner VARCHAR(21) COLLATE utf8mb4_bin NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (owner) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS zone_entries (
    id VARCHAR(21) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
    zone_id VARCHAR(21) COLLATE utf8mb4_bin NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(16) NOT NULL,
    class VARCHAR(16) NOT NULL,
    ttl INT NOT NULL DEFAULT 3600,
    rdata TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (zone_id) REFERENCES zones (id) ON DELETE CASCADE
);

CREATE INDEX idx_zone_entries_zone_id ON zone_entries (zone_id);

CREATE INDEX idx_zone_entries_name ON zone_entries (name);
